backend:
  name: github
  repo: JM010101/memoral_html
  branch: master
  base_url: https://philip-memorial-html-a-little-better.com
  auth_endpoint: api/auth

media_folder: "images"
public_folder: "images"

collections:
  - name: "memorials"
    label: "Memorials"
    folder: "data"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Memorial ID", name: "id", widget: "string"}
      - {label: "Full Name", name: "name", widget: "string"}
      - {label: "Birth Date", name: "birthDate", widget: "date"}
      - {label: "Death Date", name: "deathDate", widget: "date"}
      - {label: "Tribute", name: "tribute", widget: "text"}
      - label: "Photos"
        name: "photos"
        widget: "list"
        fields:
          - {label: "Photo", name: "url", widget: "image"}
          - {label: "Description (Alt Text)", name: "alt", widget: "string"}
